Kernel360/E2E1-TeachMe

src/main/java/kr/kernel360/teachme/lecture/entity/Category.java
src/main/java/kr/kernel360/teachme/lecture/entity/Learning.java
src/main/java/kr/kernel360/teachme/lecture/entity/Lecture.java
src/main/java/kr/kernel360/teachme/member/entity/Member.java
src/main/java/kr/kernel360/teachme/member/entity/MemberType.java
src/main/java/kr/kernel360/teachme/member/entity/MemberTypeConverter.java
src/main/java/kr/kernel360/teachme/review/entity/Review.java

오늘 기획한 ERD 를 토대로 Entity 클래스를 Spring-Data-JPA 를 통한 매핑 작업을 했습니다.
프로젝트 구조를 도메인별로 나누어 설계하였으니 해당 부분 확인해주세요!
또한 Entity 를 설계하다보니 기존 기획한 ERD 도 수정사항이 생겼는데 제가 직접 수정을 못해서 이부분 확인 부탁드립니다!
related issue: #3

Feat: add Mapped Entity 

---

src/main/java/kr/kernel360/teachme/lecture/service/InflearnLectureListCrawlingService.java

InflearnLectureListCrawlingService 부분을 모듈화 하였습니다.
main 메서드에는 최대한 로직이 들어가지 않게하고,
크롤링 자체를 실행하는 메서드와 해당 데이터를 가지고 object를 build하는 메서드로 나누었습니다.
이부분 확인하고 리뷰해주세요 :)
related issue: #19

refactor: InflearnLecureListCrawlingService

---

build.gradle
src/main/java/kr/kernel360/teachme/lecture/dto/InflearnLectureListResponse.java
src/main/java/kr/kernel360/teachme/lecture/entity/Inflearn.java
src/main/java/kr/kernel360/teachme/lecture/model/InflearnRequest.java
src/main/java/kr/kernel360/teachme/lecture/repository/InflearnRepository.java

feat: add crawling entity #22 

---

src/main/java/kr/kernel360/teachme/lecture/dto/FastcampustLectureResponse.java

fix: modify fastcampus dto #26

---

src/main/java/kr/kernel360/teachme/exception/CrawlerException.java
src/main/java/kr/kernel360/teachme/lecture/service/InflearnLectureListCrawlingService.java
src/main/resources/templates/crawler/crawlerForm.html
src/main/resources/templates/layout/defaultLayout.html

인프런 크롤러의 기능을 추가했습니다.
1. 인프런 크롤링 시 inflearn lecture 테이블의 데이터가 있는지 없는지를 검사합니다 (있다면 exception을 반환합니다)
2. 인프런 크롤링 사이트 및 ui를 개선하였습니다.
해당 부분 확인하시고 리뷰 부탁드립니다 :)
related issue: #33

feat: update inflearn crawler

---

src/main/java/kr/kernel360/teachme/lecture/controller/LectureController.java
src/main/java/kr/kernel360/teachme/lecture/service/LectureService.java
src/main/resources/static/style/home.css
src/main/resources/static/style/lecture/list.css
src/main/resources/templates/fragments/clientAdvertise.html
src/main/resources/templates/fragments/clientHeader.html
src/main/resources/templates/home.html
src/main/resources/templates/lecture/list.html

강의 리스트 페이지를 개괄적으로 디자인 하고 아주 간단한 페이징 기능을 추가했습니다.
해당 페이지는 저희 아이디어 넣어서 디자인을 꾸며봐도 좋을 것 같아요~! 
우선은 이 디자인으로 발표를 위해 pr 날립니다.
리뷰 부탁드려요~
related issue: #62

Update feature pagination in lecture list page

---

src/main/java/kr/kernel/teachme/lecture/controller/CrawlerController.java
src/main/java/kr/kernel/teachme/lecture/controller/HomeController.java
src/main/java/kr/kernel/teachme/lecture/controller/LectureController.java
src/main/java/kr/kernel/teachme/lecture/dto/CrawlingResponse.java
src/main/java/kr/kernel/teachme/lecture/dto/FastcampusLectureListResponse.java
src/main/java/kr/kernel/teachme/lecture/dto/InflearnLectureDetailResponse.java
src/main/java/kr/kernel/teachme/lecture/dto/Pagination.java
src/main/java/kr/kernel/teachme/lecture/dto/PaginationResponse.java
src/main/java/kr/kernel/teachme/lecture/entity/FastcampusLecture.java
src/main/java/kr/kernel/teachme/lecture/entity/InflearnLecture.java
src/main/java/kr/kernel/teachme/lecture/service/InflearnLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/lecture/service/LectureService.java
src/main/resources/static/js/crawler.js
src/main/resources/templates/crawler/crawlerForm.html

인프런 상세 정보 크롤링 기능을 업데이트 하였습니다.
해당 사항 참고해서 패스트 캠퍼스 상세 정보 크롤링 기능을 추가해주시면 감사드리겠습니다.
또한 인프런은 너무 많은 요청이 발생 시 403 에러를 발생시킬 수 있어 현재는 50개씩 크롤링 하도록 제한이 있는 상태입니다.
이부분 배포시나 전체 통합 테스트시 반복문 안의 break문을 삭제 혹은 주석처리 시켜주시기 바랍니다.
리뷰 부탁드립니다 :)

feat: update inflearn detail crawler

---

src/main/java/kr/kernel/teachme/lecture/dto/InflearnLectureDetailResponse.java
src/main/java/kr/kernel/teachme/lecture/entity/InflearnLecture.java
src/main/java/kr/kernel/teachme/lecture/repository/FastcampusRepository.java
src/main/java/kr/kernel/teachme/lecture/repository/LectureRepository.java
src/main/java/kr/kernel/teachme/lecture/service/FastcampusLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/lecture/service/InflearnLectureDetailCrawlingService.java

feat: fix inflearnDetailCrawlingservice - add updateDate, postDate fix FastcampusDetailCrawlingService error #74

feat: fix inflearnDetailCrawlingservice - add updateDate, postDate fix FastcampusDetailCrawlingService error

---

src/main/java/kr/kernel/teachme/crawler/dto/FastcampusLectureResponse.java
src/main/java/kr/kernel/teachme/crawler/dto/InflearnLectureListResponse.java
src/main/java/kr/kernel/teachme/crawler/entity/FastcampusLecture.java
src/main/java/kr/kernel/teachme/crawler/entity/InflearnLecture.java
src/main/java/kr/kernel/teachme/crawler/service/FastcampusLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/crawler/service/FastcampusLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/crawler/service/InflearnLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/crawler/service/InflearnLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/lecture/entity/Lecture.java
src/main/java/kr/kernel/teachme/lecture/repository/LectureRepository.java

fix : 인프런 패스트캠퍼스 테이블 통합 진행 #81

fix : 인프런 패스트캠퍼스 테이블 통합 진행 #81

---

src/main/java/kr/kernel/teachme/crawler/dto/FastcampusLectureResponse.java
src/main/java/kr/kernel/teachme/crawler/dto/InflearnLectureListResponse.java
src/main/java/kr/kernel/teachme/crawler/entity/FastcampusLecture.java
src/main/java/kr/kernel/teachme/crawler/entity/InflearnLecture.java
src/main/java/kr/kernel/teachme/crawler/service/FastcampusLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/crawler/service/FastcampusLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/crawler/service/InflearnLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/crawler/service/InflearnLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/lecture/entity/Lecture.java
src/main/java/kr/kernel/teachme/lecture/repository/LectureRepository.java

Topic #81 fix : 인프런 패스트캠퍼스 테이블 통합 진행
아직 수정 중이며 짝코딩을 위해 업로드 진행함.
수정 된 곳은 inflearnLectureListCrawlingService이며 추가적으로 Detail 및 entity가 수정됨

Topic #81 fix : 인프런 패스트캠퍼스 테이블 통합 진행

---

build.gradle
src/main/java/kr/kernel/teachme/config/QuerydslConfiguration.java
src/main/java/kr/kernel/teachme/config/SpringSecurityConfig.java
src/main/java/kr/kernel/teachme/crawler/dto/InflearnLectureListResponse.java
src/main/java/kr/kernel/teachme/lecture/repository/LectureRepository.java
src/main/java/kr/kernel/teachme/lecture/repository/LectureRepositoryCustom.java
src/main/java/kr/kernel/teachme/lecture/repository/LectureRepositoryCustomImpl.java

Querydsl을 이용한 검색 기능 구현 진행 (페어 프로그래밍)

feat: add QuerydslSearch in Repository

---

src/main/resources/static/style/lecture/list.css
src/main/resources/templates/lecture/list.html

검색 기능 구현을 위해 QueryDSL 을 이용해 동적 쿼리를 생성하였고 해당 검색 조건에 맞게 페이지 디자인을 수정하였습니다.
데이터 요청 Object 의 Setter 메서드에 로직을 추가해 데이터 validation을 진행하도록 수정하였습니다.
해당 부분 확인해주시고 리뷰 부탁드립니다 :)
related issue: #88

feat: update search lecture list

---

src/main/java/kr/kernel/teachme/lecture/controller/LectureController.java
src/main/java/kr/kernel/teachme/lecture/service/LectureService.java
src/main/resources/templates/lecture/detail.html

feat : add lectureDetail link lectureList page #99 
detail.html 추가됨 (연결만 확인)
LectureService -> getLectureDetail 추가됨 (상세 페이지로 연결)

feat : add lectureDetail link lectureList page #98

---

.gitignore
build.gradle
log/application.log
src/main/java/kr/kernel/teachme/TeachmeApplication.java
src/main/java/kr/kernel/teachme/common/aop/LogAspect.java
src/main/resources/logback-spring.xml

Spring AOP를 사용해서 로그 기능을 추가했습니다. 
related issue #105

feat : log with spring aop

---

src/main/java/kr/kernel/teachme/TeachmeApplication.java
src/main/java/kr/kernel/teachme/common/aop/LogAspect.java
src/main/java/kr/kernel/teachme/common/config/InitializeDefaultConfig.java
src/main/java/kr/kernel/teachme/domain/crawler/component/AutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/component/InfleanAutoCrawler.java
src/main/java/kr/kernel/teachme/domain/lecture/entity/Lecture.java
src/main/java/kr/kernel/teachme/domain/lecture/repository/LectureRepository.java

패캠, 인프런의 크롤링 자동화를 위한 서비스 로직을 구현하기 전, interface를 먼저 구현했습니다.
추후 패캠, 인프런 강의 크롤링 자동화 로직 구현 시 implements 하여 구현하면 될 것 같습니다. 
related issue: #111

feat: AutoCrawler interface

---

src/main/java/kr/kernel/teachme/domain/member/controller/FavorController.java
src/main/java/kr/kernel/teachme/domain/member/entity/MemberFavor.java
src/main/java/kr/kernel/teachme/domain/member/repository/MemberFavorRepository.java
src/main/java/kr/kernel/teachme/domain/member/service/MemberFavorService.java
src/main/resources/static/css/lecture/detail.css
src/main/resources/templates/member/favor.html

찜 기능 구현 중이며 구현 중에 문제가 발생하여 오늘 진행한 부분까지 올립니다.
이후 수정하여 다시 올릴 예정이며 페이징이 어려워 일단 리스트만 불러올 수 있도록 진행하려고 합니다.

feat: add favor Business logic ~ing

---

src/main/java/kr/kernel/teachme/common/config/InitializeDefaultConfig.java
src/main/java/kr/kernel/teachme/common/util/DateUtil.java
src/main/java/kr/kernel/teachme/domain/crawler/component/AutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/component/FastcampusAutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/component/InfleanAutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/dto/FastcampusLectureDetailResponse.java
src/main/java/kr/kernel/teachme/domain/crawler/dto/FastcampusLectureResponse.java
src/main/java/kr/kernel/teachme/domain/crawler/dto/FastcampusLectureUpdateResponse.java
src/main/java/kr/kernel/teachme/domain/lecture/entity/Lecture.java

현재 autocrawlling을 위한 modelmapper 수정 중에 있습니다.
이 후 inflearn도 동일한 수정 작업 필요합니다.

feat: add fastcampusAutocrawler

---

src/main/java/kr/kernel/teachme/domain/crawler/component/AutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/component/FastcampusAutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/component/InflearnAutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/dto/InflearnLectureDetailResponse.java
src/main/java/kr/kernel/teachme/domain/crawler/service/InflearnLectureDetailCrawlingService.java
src/main/java/kr/kernel/teachme/domain/lecture/entity/Lecture.java

인프런 부분도 자동적으로 scheduler 에 따라 크롤링을 수행하도록 로직을 수정하였습니다.
현재 인프런 부분 가격을 가져오는 부분이 굉장히 난해 해서 해당 부분은 수정 예정임을 참고 부탁드립니다!
리뷰 부탁드립니다.
related issue: #111

feat: add new feature to crawl inflearn data automatically

---

src/main/java/kr/kernel/teachme/domain/review/controller/ReviewController.java
src/main/java/kr/kernel/teachme/domain/review/dto/ReviewRequest.java
src/main/java/kr/kernel/teachme/domain/review/dto/ReviewResponse.java
src/main/java/kr/kernel/teachme/domain/review/entity/Review.java
src/main/java/kr/kernel/teachme/domain/review/repository/ReviewRepository.java
src/main/java/kr/kernel/teachme/domain/review/service/ReviewService.java

feat : add review C,D #124 
리뷰 관련 CRD 작성 진행했습니다.
아직 U는 작성하지 못했습니다.

feat : add review C,D

---

src/main/java/kr/kernel/teachme/common/config/SpringSecurityConfig.java
src/main/java/kr/kernel/teachme/common/jwt/JwtAuthorizationFilter.java
src/main/java/kr/kernel/teachme/domain/member/repository/MemberRepository.java
src/main/java/kr/kernel/teachme/domain/member/service/MemberService.java
src/main/java/kr/kernel/teachme/domain/review/service/ReviewService.java
src/test/java/kr/kernel/teachme/domain/member/service/MemberServiceTest.java

MemberRepository의 findbyusername 부분의 return값을 optional로 수정하고, 클래스가 memberrepository의 findbyusername을 사용한다면, memberservice의 findbyusername을 쓰도록 수정했습니다. 
related issue: #128

feat: modify MemberServiceTest

---

build.gradle
src/main/java/kr/kernel/teachme/common/config/SpringSecurityConfig.java
src/main/java/kr/kernel/teachme/common/jwt/JwtAuthenticationFilter.java
src/main/java/kr/kernel/teachme/common/jwt/JwtAuthorizationFilter.java
src/main/java/kr/kernel/teachme/common/jwt/JwtUtils.java
src/main/java/kr/kernel/teachme/domain/crawler/service/FastcampusLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/domain/lecture/controller/LectureController.java
src/test/java/kr/kernel/teachme/common/config/PasswordEncoderConfigTest.java
src/test/java/kr/kernel/teachme/common/config/SpringSecurityConfigTest.java
src/test/java/kr/kernel/teachme/common/jwt/JwtAuthenticationFilterTest.java
src/test/java/kr/kernel/teachme/common/jwt/JwtAuthorizationFilterTest.java
src/test/java/kr/kernel/teachme/common/jwt/JwtUtilsTest.java

jwt 토큰 검증 테스트 코드를 작성 및 테스트 코드 작성 도중 로직을 보완하였습니다.

feat: add test for jwt auth logic

---

src/main/java/kr/kernel/teachme/common/util/StringUtil.java
src/main/java/kr/kernel/teachme/domain/crawler/component/FastcampusAutoCrawler.java
src/main/java/kr/kernel/teachme/domain/crawler/service/InflearnLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/domain/lecture/entity/Lecture.java
src/main/java/kr/kernel/teachme/domain/lecture/service/LectureService.java
src/main/java/kr/kernel/teachme/domain/member/entity/MemberFavorLecture.java
src/main/java/kr/kernel/teachme/domain/member/service/MemberService.java
src/main/resources/static/js/home.js
src/main/resources/templates/home.html
src/test/java/kr/kernel/teachme/common/jwt/JwtAuthenticationFilterTest.java
src/test/java/kr/kernel/teachme/common/jwt/JwtAuthorizationFilterTest.java
src/test/java/kr/kernel/teachme/domain/lecture/dto/PaginationResponseTest.java
src/test/java/kr/kernel/teachme/domain/lecture/dto/PaginationTest.java
src/test/java/kr/kernel/teachme/domain/lecture/dto/SearchRequestTest.java
src/test/java/kr/kernel/teachme/domain/lecture/entity/LectureTest.java
src/test/java/kr/kernel/teachme/domain/lecture/repository/LecutreRepositoryCustomImplTest.java
src/test/java/kr/kernel/teachme/domain/lecture/service/LectureServiceTest.java

Lecture 도메인에 대한 테스트 코드를 작성하고 해당 코드에 맞춰 리팩토링을 진행하였습니다.
해당 사항 참고(만) 하셔서 나머지 도메인에 대한 테스트 코드 작성 및 리팩토링 진행하면 될 것 같습니다.
(참고로 아직 테스트 코드에 미숙한 점이 많아 작성된 테스트 코드중 일부는 통과되지 않아요..)
확인하시고 리뷰 주시면 고칠 수 있는 부분 고치도록 하겠습니다.
감사합니다.

feat: add testcode for lecture domain

---

src/main/java/kr/kernel/teachme/domain/crawler/service/FastcampusLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/domain/crawler/service/InflearnLectureListCrawlingService.java
src/main/java/kr/kernel/teachme/domain/review/entity/Review.java
src/main/resources/templates/fragments/integration.html

수동 크롤러가 Url 을 불러오지 못해 작동하지 않았던 오류를 수정했습니다.
(static 이 아니면 안되는 곳이 static이었네요..)
리뷰하시고 병합 부탁드립니다

fix: fix url for crawler service

---

src/main/java/kr/kernel/teachme/domain/lecture/repository/LectureRepositoryCustomImpl.java
src/main/java/kr/kernel/teachme/domain/member/controller/MyPageController.java
src/main/resources/templates/fragments/integration.html
src/main/resources/templates/member/login.html
src/main/resources/templates/member/mypage.html

헤더에 스타일을 추가하였습니다 :)
확인 후 리뷰 부탁드려용..!

style: add style for login button and logout button

---

src/main/java/kr/kernel/teachme/domain/lecture/repository/LectureRepositoryCustomImpl.java
src/main/java/kr/kernel/teachme/domain/member/controller/MyPageController.java
src/main/resources/templates/fragments/integration.html
src/main/resources/templates/member/login.html
src/main/resources/templates/member/mypage.html

헤더 메뉴의 로그인 버튼, 로그아웃, 회원가입 버튼에 스타일을 추가하였습니다.
확인 부탁드려요~!
related issue: #163

style: add style for header menu

---

src/main/resources/templates/crawler/crawlerForm.html

fix : reopen admin page crawl button

fix : reopen admin page crawl button
